# Generated by Django 2.0 on 2018-01-20 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wemo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='memo_title',
            field=models.CharField(max_length=77),
        ),
    ]
